#ifndef LINES
#define LINES 20
#define COLUMNS 10
#define BLOCK_SIZE 30
#define FIELD_W COLUMNS * BLOCK_SIZE
#define FIELD_H LINES   * BLOCK_SIZE
#define MAX_FALL_COOLDOWN 20
#define BG_COLOR 98, 45, 138
#define PIECE_COLOR 255, 255, 255
#endif